torchrun --nproc_per_node=1 train.py \
	--h1 32 --h2 32 \
    --n-ranks 10 \
    --epochs 2000 \
    --lr 1e-3\
    --batch-size 16384 \
    --n-seeds 1 \
	 --print-every 50 \
    --folder ./data \
    --model-file ./friction_emulator.txt \
    --checkpoint ./friction_emulator.pt \
	 --device auto \
	 --normalization log
